kind: Service
apiVersion: v1
metadata:
  name: phpmyadmin-lb
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
    # service.beta.kubernetes.io/do-loadbalancer-healthcheck-path: "/wp-login.php"
spec:
  type: LoadBalancer
  selector:
    app: phpmyadmin
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80