apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${WP_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${WP_NAME}
  template:
    metadata:
      labels:
        app: ${WP_NAME}
    spec:
      containers:
        - name: ${WP_NAME}
          image: wordpress:6.5.3-php8.1-apache
          #image: wordpress:5-php7.1-apache
          ports:
          - containerPort: 80
            name: ${WP_NAME}
          volumeMounts:
            - name: ${WP_NAME}-data
              mountPath: /var/www
            # - name: apache-config
            #   mountPath: /etc/apache2/sites-available/000-default.conf
            #   subPath: apache.conf
          env:
            # Annoyingly repetitive -- envFrom: is a nicer way to do this with a ConfigMap or Secret
            - name: WORDPRESS_DB_HOST
              value: mysql.default.svc.cluster.local
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wp-db-secrets
                  key: MYSQL_ROOT_PASSWORD
            - name: WORDPRESS_DB_USER
              value: root
            - name: WORDPRESS_DB_NAME
              value: ${MYSQL_DATABASE}
      volumes:
        - name: ${WP_NAME}-data
          persistentVolumeClaim:
            claimName: ${WP_NAME}-volume
        # - name: apache-config
        #   configMap:
        #     name: apache-config
        #     items:
        #       - key: apache.conf
        #         path: apache.conf